feature_columns:
- ind_EMA
- ind_MACD_12_26_9
- ind_MACD_SIGNAL_12_26_9
- ind_MACD_hist
- ind_RSI_14
- pat_DOJI
- pat_ENGULFING
- close
- volume
n_features: 9
target_column: target
timestamp_column: datetime
steps:
- method: fractional_differencing
  params:
    d: 0.2
    threshold: 0.001
- method: robust_scaler
  params: {}
fitted_methods:
- fractional_differencing
- robust_scaler
