// Dark theme tokens — matches the reference dashboard (near-black bg, mint accent, glass panels)
export const colors = {
  bg: '#0B0E11',
  panel: '#12161B',
  panelAlt: '#161B21',
  border: 'rgba(255, 255, 255, 0.07)',
  borderStrong: 'rgba(255, 255, 255, 0.12)',
  textPrimary: '#F5F6F7',
  textSecondary: '#9096A0',
  textTertiary: '#6B7280',
  mint: '#3DDC97',
  mintSoft: 'rgba(61, 220, 151, 0.12)',
  red: '#F0466B',
  redSoft: 'rgba(240, 70, 107, 0.12)',
  amber: '#FF8A5C',
};

export const themeConfig = {
  token: {
    colorPrimary: colors.mint,
    colorBgBase: colors.bg,
    colorBgContainer: colors.panel,
    colorBgElevated: colors.panelAlt,
    colorTextBase: colors.textPrimary,
    colorText: colors.textPrimary,
    colorTextSecondary: colors.textSecondary,
    colorSuccess: colors.mint,
    colorError: colors.red,
    colorBorder: colors.border,
    colorBorderSecondary: colors.border,
    borderRadius: 12,
    borderRadiusLG: 18,
    fontFamily: "'Geist Variable', system-ui, -apple-system, sans-serif",
    colorLink: colors.mint,
    colorLinkHover: colors.mint,
  },
  components: {
    Layout: {
      siderBg: 'transparent',
      headerBg: 'transparent',
      bodyBg: colors.bg,
    },
    Menu: {
      itemBg: 'transparent',
      darkItemBg: 'transparent',
      itemColor: colors.textSecondary,
      itemSelectedBg: colors.mint,
      itemSelectedColor: '#0B0E11',
      itemHoverBg: 'rgba(255, 255, 255, 0.04)',
      itemHoverColor: colors.textPrimary,
      itemHeight: 46,
      itemBorderRadius: 12,
      iconSize: 17,
      fontSize: 14.5,
    },
    Card: {
      colorBgContainer: colors.panel,
      borderRadiusLG: 20,
      colorBorderSecondary: colors.border,
    },
    Table: {
      colorBgContainer: 'transparent',
      headerBg: 'transparent',
      headerColor: colors.textTertiary,
      borderColor: colors.border,
      rowHoverBg: 'rgba(255, 255, 255, 0.03)',
      colorText: colors.textPrimary,
    },
    Input: {
      colorBgContainer: 'rgba(255, 255, 255, 0.04)',
      colorBorder: colors.border,
      colorTextPlaceholder: colors.textTertiary,
      colorText: colors.textPrimary,
      activeBorderColor: colors.mint,
      hoverBorderColor: colors.borderStrong,
    },
    Select: {
      colorBgContainer: 'rgba(255, 255, 255, 0.04)',
      colorBgElevated: colors.panelAlt,
      colorBorder: colors.border,
      colorText: colors.textPrimary,
      colorTextPlaceholder: colors.textTertiary,
      colorTextQuaternary: colors.textTertiary,
      activeBorderColor: colors.mint,
      hoverBorderColor: colors.borderStrong,
      optionSelectedBg: colors.mintSoft,
      optionSelectedColor: colors.textPrimary,
      optionActiveBg: 'rgba(255, 255, 255, 0.06)',
    },
    DatePicker: {
      colorBgContainer: 'rgba(255, 255, 255, 0.04)',
      colorBgElevated: colors.panelAlt,
      colorBorder: colors.border,
      colorText: colors.textPrimary,
      colorTextPlaceholder: colors.textTertiary,
      colorTextDisabled: colors.textTertiary,
      activeBorderColor: colors.mint,
      hoverBorderColor: colors.borderStrong,
      // Selected day cell (e.g. the "26" start-date circle)
      cellActiveWithRangeBg: colors.mintSoft,
      // In-range cells between start/end dates — this is what was
      // unreadable: light mint bg with light text in the screenshot
      cellHoverWithRangeBg: 'rgba(61, 220, 151, 0.18)',
      cellRangeBorderColor: colors.mint,
    },
    Tag: {
      colorBgContainer: colors.panelAlt,
    },
    Tooltip: {
      colorBgSpotlight: colors.panelAlt,
      colorTextLightSolid: colors.textPrimary,
    },
    Avatar: {
      colorTextPlaceholder: colors.textPrimary,
    },
  },
};